version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: always
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - '3000:3333'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}

      DATABASE_URL: 'postgres://postgres:postgres@postgres:5432/base_app_development'
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: base_app_development
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  database:
